package Ftw;

public enum Msg {TIMEOUT, BACK_TO_IDLE, SUCCESSFUL_SEND, SUCCESSFUL_SELECT, SUCCESSFUL_FINISHED,
	SUCCESSFUL_RESEND, FAILED_ACK, SUCCESSFUL_CONNECT, SUCCESSFUL_ACK, START, SENDING, WAIT, GO_TO_SENDING}
